### ISSUE TITLE
Downstream transform fails due to missing synonym values

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/phenio#20]
### Describe the bug

Transform of `phenio.owl` to KG-Phenio fails due to nodes from PLANA and WBPhenotype missing values for synonym predicates.
e.g.
```
    <rdf:Description rdf:about="http://purl.obolibrary.org/obo/WBPhenotype_0001117">
        <obo:IAO_0000115>Cell-cell contacts are abnormal in the early embryo.</obo:IAO_0000115>
        <oboInOwl:hasOBONamespace>C_elegans_phenotype_ontology</oboInOwl:hasOBONamespace>
        <oboInOwl:hasNarrowSynonym></oboInOwl:hasNarrowSynonym>
        <oboInOwl:hasBroadSynonym>Emb</oboInOwl:hasBroadSynonym>
        <oboInOwl:id>WBPhenotype:0001117</oboInOwl:id>
        <rdfs:label>cell cell contacts abnormal early emb (WBP)</rdfs:label>
```

See also https://github.com/Knowledge-Graph-Hub/kg-phenio/issues/73

### Version

Release 2022-09-28

**Comment by matentzn** [comment]
The pipeline should be made resilient to this failure of course, but this does not mean I should not try and fix the root cause.

- https://github.com/obophenotype/c-elegans-phenotype-ontology/pull/181
- https://github.com/obophenotype/planaria-ontology/issues/208
- The PLANA issue was already fixed in the release - Will be fixed as part of https://github.com/obophenotype/planarian-phenotype-ontology/issues/15

**Comment by caufieldjh** [comment]
Validation for this is in KG-Phenio as of https://github.com/Knowledge-Graph-Hub/kg-phenio/pull/74
