### ISSUE TITLE
Dangling NCBITAXON edges are present

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/phenio#24]
### Describe the bug

As per @matentzn, dangling NCBITAXON edges are present.

PHENIO uses the [taxon slim](http://purl.obolibrary.org/obo/ncbitaxon/subsets/taxslim.owl).

**Comment by matentzn** [comment]
This is not actually a bug in the strict sense. This is a slightly complex issue because it establishes a dependency of PHENIO on the KG - which we want to avoid. Here is my suggestion (run by @cmungall in your next meeting with him).

1. We mirror the entire NCBITAXON slim and merge it into Phenio (no subsetting)
2. We add all the IDs currently needed by the ingest to NCBITAXON slim
3. We create a QC check somewhere at ingestion time that warns of dangling NCBI taxons with the necessity to curate them into the slim

My 2 cents, could be wrong.

**Comment by matentzn** [comment]
Fixed by #94
